/**
 * Protection catalog – the single source of truth for
 *   1. validating / clamping the per-server configuration (backend),
 *   2. rendering the settings forms (dashboard fetches it via /api/meta/catalog),
 *   3. the Lua schema of the FiveM resource (generated by `npm run gen:lua-schema`).
 *
 * To add a protection: add an entry here, run `npm run gen:lua-schema`, implement the
 * handler in resource/fxshield/server/. The dashboard picks it up automatically.
 */

export const CONFIG_VERSION = 1

export interface IntField {
  type: 'int'
  key: string
  label: string
  help?: string
  unit?: string
  min: number
  max: number
  default: number
}
export interface BoolField {
  type: 'bool'
  key: string
  label: string
  help?: string
  default: boolean
}
export interface SelectField {
  type: 'select'
  key: string
  label: string
  help?: string
  options: { value: string; label: string }[]
  default: string
}
export interface TextField {
  type: 'text'
  key: string
  label: string
  help?: string
  maxLength: number
  default: string
}
export type Field = IntField | BoolField | SelectField | TextField
export type FieldValue = number | boolean | string

export interface ModeDef {
  value: string
  label: string
  description: string
}

export type ProtectionGroup = 'connections' | 'ingame'

export interface ProtectionDef {
  id: string
  group: ProtectionGroup
  title: string
  summary: string
  /** Shown as a badge: the protection needs OneSync to work. */
  requiresOneSync?: boolean
  /** Honest warning shown in the dashboard (side effects, limits). */
  caveat?: string
  modes: ModeDef[]
  defaultMode: string
  fields: Field[]
}

export interface Config {
  v: number
  general: Record<string, FieldValue>
  /** per protection: `mode` + its fields */
  protections: Record<string, Record<string, FieldValue>>
  messages: Record<string, string>
}

// ───────────────────────────── field helpers ─────────────────────────────

const int = (
  key: string,
  label: string,
  min: number,
  max: number,
  def: number,
  extra: { unit?: string; help?: string } = {},
): IntField => ({ type: 'int', key, label, min, max, default: def, ...extra })

const bool = (key: string, label: string, def: boolean, help?: string): BoolField => ({
  type: 'bool',
  key,
  label,
  default: def,
  ...(help ? { help } : {}),
})

const select = (
  key: string,
  label: string,
  options: [string, string][],
  def: string,
  help?: string,
): SelectField => ({
  type: 'select',
  key,
  label,
  options: options.map(([value, lbl]) => ({ value, label: lbl })),
  default: def,
  ...(help ? { help } : {}),
})

const text = (key: string, label: string, maxLength: number, def: string, help?: string): TextField => ({
  type: 'text',
  key,
  label,
  maxLength,
  default: def,
  ...(help ? { help } : {}),
})

const STD_MODES: ModeDef[] = [
  { value: 'off', label: 'Off', description: 'Protection is disabled.' },
  { value: 'monitor', label: 'Monitor', description: 'Detect and report only – nothing is blocked. Use this to tune limits safely.' },
  { value: 'enforce', label: 'Enforce', description: 'Detect and act (block, cancel, kick or ban).' },
]

const ACTIONS: [string, string][] = [
  ['cancel', 'Cancel only'],
  ['kick', 'Cancel + kick'],
  ['tempban', 'Cancel + temporary ban'],
]

// ───────────────────────────── the catalog ─────────────────────────────

export const GENERAL_FIELDS: Field[] = [
  int('pollIntervalSec', 'Sync interval', 5, 60, 10, {
    unit: 'seconds',
    help: 'How often the resource contacts the backend (config, blocklist, statistics). Changes made in the dashboard reach the server within this time.',
  }),
]

export const MESSAGE_FIELDS: TextField[] = [
  text('blocked', 'Generic rejection', 200, 'Connection rejected by FX Shield.'),
  text('banned', 'Blocklist / temporary ban', 200, 'You are banned from this server.'),
  text('rateLimited', 'Too many attempts', 200, 'Too many connection attempts. Please wait a moment and try again.'),
  text('attackMode', 'Under-attack mode', 200, 'The server is under attack and currently only accepts returning players. Please try again later.'),
  text('invalidIdentity', 'Missing / invalid license', 200, 'Your Rockstar license could not be verified.'),
  text('invalidName', 'Invalid player name', 200, 'Your player name contains invalid characters. Please change it and reconnect.'),
  text('tooManyPerIp', 'Too many players per IP', 200, 'Too many players are already connected from your network.'),
  text('kicked', 'Kick for abuse', 200, 'You were removed from the server for abusive behaviour.'),
]

export const PROTECTIONS: ProtectionDef[] = [
  {
    id: 'connectionFlood',
    group: 'connections',
    title: 'Connection flood guard',
    summary: 'Rate-limits connection attempts per IP address and per Rockstar license and temporarily bans offenders.',
    caveat:
      'IP based limits need real player IPs, but FXServer hides them by default (sv_endpointprivacy): add "sv_endpointprivacy false" to your server.cfg. Without it only the license limits work. Behind a proxy, it must pass the real client IP on.',
    modes: STD_MODES,
    defaultMode: 'enforce',
    fields: [
      int('maxAttemptsPerIp', 'Max. attempts per IP', 1, 200, 10, {
        unit: 'attempts',
        help: 'Connection attempts a single IP address may make within the time window.',
      }),
      int('maxAttemptsPerLicense', 'Max. attempts per license', 1, 200, 6, {
        unit: 'attempts',
        help: 'Connection attempts a single Rockstar license may make within the time window.',
      }),
      int('windowSec', 'Time window', 5, 600, 30, { unit: 'seconds' }),
      int('banSec', 'Temporary ban', 0, 604800, 300, {
        unit: 'seconds',
        help: 'How long an offender stays blocked after exceeding a limit. 0 = only reject the attempt, no ban.',
      }),
    ],
  },
  {
    id: 'playersPerIp',
    group: 'connections',
    title: 'Accounts per IP',
    summary: 'Limits how many players may be connected from the same IP address at the same time (slot-filling bots, multi-accounting).',
    caveat: 'Households, internet cafés and mobile carriers share IP addresses – keep the limit generous.',
    modes: STD_MODES,
    defaultMode: 'monitor',
    fields: [int('maxPlayers', 'Max. players per IP', 1, 128, 4, { unit: 'players' })],
  },
  {
    id: 'identityCheck',
    group: 'connections',
    title: 'Identity & name check',
    summary: 'Rejects clients without a verifiable license and player names that are empty, oversized or contain hidden / control characters.',
    modes: STD_MODES,
    defaultMode: 'enforce',
    fields: [
      bool('requireLicense', 'Require Rockstar license', true, 'Rejects connections without a license / license2 identifier. Skipped automatically when sv_lan is enabled.'),
      int('maxNameLength', 'Max. name length', 8, 200, 100, { unit: 'characters' }),
      bool('blockHiddenChars', 'Block hidden characters', true, 'Control characters, zero-width spaces and bidirectional overrides in names.'),
      bool('blockEmptyName', 'Block empty names', true),
    ],
  },
  {
    id: 'attackMode',
    group: 'connections',
    title: 'Under-attack mode',
    summary:
      'Detects connection floods and then tightens the per-IP limits and (optionally) only lets returning players in until the attack is over.',
    caveat: 'While active and set to "block", players who have never joined this server before cannot connect. The dashboard shows when it is active.',
    modes: [
      { value: 'off', label: 'Off', description: 'Never activate.' },
      { value: 'monitor', label: 'Monitor', description: 'Detect attacks and report them, but never change behaviour.' },
      { value: 'auto', label: 'Automatic', description: 'Activate automatically when the thresholds are exceeded.' },
      { value: 'on', label: 'Always on', description: 'Force under-attack mode now (panic switch).' },
    ],
    defaultMode: 'auto',
    fields: [
      int('triggerBlockedPerMin', 'Trigger: rejected attempts / min', 5, 10000, 40, {
        unit: 'per minute',
        help: 'Attack mode starts when this many connection attempts were rejected within the last minute.',
      }),
      int('triggerAttemptsPerMin', 'Trigger: total attempts / min', 20, 100000, 600, {
        unit: 'per minute',
        help: 'Attack mode also starts when this many connection attempts (accepted or not) arrive within a minute. Must be above your normal peak, e.g. a full-server restart.',
      }),
      int('minDurationSec', 'Minimum duration', 30, 3600, 180, { unit: 'seconds', help: 'Attack mode stays active at least this long after the last trigger.' }),
      select(
        'newPlayers',
        'New players during an attack',
        [
          ['allow', 'Allow (only tighter limits)'],
          ['block', 'Block (returning players only)'],
        ],
        'block',
        'Returning = this license has joined this server before.',
      ),
      int('limitPercent', 'Per-IP limit during attack', 10, 100, 50, {
        unit: '% of normal',
        help: 'The per-IP connection limit is scaled down to this percentage while the attack lasts.',
      }),
    ],
  },
  {
    id: 'gameEventFlood',
    group: 'ingame',
    title: 'Game event flood guard',
    summary:
      'Caps explosions, particle effects, fires and projectiles a single client can create. Stops modded clients from crashing or lagging the server with event spam.',
    requiresOneSync: true,
    modes: STD_MODES,
    defaultMode: 'enforce',
    fields: [
      int('windowSec', 'Time window', 1, 60, 5, { unit: 'seconds' }),
      int('maxExplosions', 'Max. explosions', 1, 1000, 15, { unit: 'per window' }),
      int('maxParticles', 'Max. particle effects', 1, 2000, 120, { unit: 'per window' }),
      int('maxFires', 'Max. fires', 1, 1000, 30, { unit: 'per window' }),
      int('maxProjectiles', 'Max. projectiles', 1, 1000, 25, { unit: 'per window' }),
      select('action', 'When a client keeps going', ACTIONS, 'cancel', 'Events above the limit are always cancelled. Kick / ban only happens after the strike threshold below.'),
      int('strikes', 'Strikes before punishment', 1, 1000, 30, {
        unit: 'cancelled events / 60 s',
        help: 'Only used for "kick" and "temporary ban".',
      }),
      int('banSec', 'Temporary ban', 60, 604800, 3600, { unit: 'seconds' }),
    ],
  },
  {
    id: 'entitySpam',
    group: 'ingame',
    title: 'Entity spam guard',
    summary: 'Caps how many script-created entities (vehicles, peds, objects) a single client may create per time window.',
    requiresOneSync: true,
    caveat:
      'Entities spawned by your own server scripts "for" a player can be attributed to that player. Start in Monitor mode and check the event log before enforcing.',
    modes: STD_MODES,
    defaultMode: 'monitor',
    fields: [
      int('windowSec', 'Time window', 1, 60, 10, { unit: 'seconds' }),
      int('maxEntities', 'Max. entities', 5, 2000, 40, { unit: 'per window' }),
      select('action', 'When a client keeps going', ACTIONS, 'cancel'),
      int('strikes', 'Strikes before punishment', 1, 1000, 20, { unit: 'cancelled entities / 60 s' }),
      int('banSec', 'Temporary ban', 60, 604800, 3600, { unit: 'seconds' }),
    ],
  },
  {
    id: 'entityLockdown',
    group: 'ingame',
    title: 'Entity lockdown',
    summary: "Uses FXServer's built-in entity lockdown: clients are not allowed to create entities on their own.",
    requiresOneSync: true,
    caveat:
      'Breaks every resource that spawns vehicles, peds or objects on the client. Only enable it if all your resources create entities server-side.',
    modes: [
      { value: 'off', label: 'Off', description: 'Clients may create entities (default FiveM behaviour).' },
      { value: 'relaxed', label: 'Relaxed', description: 'Blocks script-created entities from clients, ambient population is still allowed.' },
      { value: 'strict', label: 'Strict', description: 'Blocks all entities created by clients.' },
    ],
    defaultMode: 'off',
    fields: [],
  },
  {
    id: 'chatFlood',
    group: 'ingame',
    title: 'Chat flood guard',
    summary: 'Limits chat messages and commands per player and the maximum message length (works with the default `chat` resource).',
    modes: STD_MODES,
    defaultMode: 'enforce',
    fields: [
      int('windowSec', 'Time window', 1, 60, 5, { unit: 'seconds' }),
      int('maxMessages', 'Max. messages', 1, 100, 8, { unit: 'per window' }),
      int('maxLength', 'Max. message length', 20, 2000, 400, { unit: 'characters' }),
      select('action', 'When a client keeps going', [['cancel', 'Cancel only'], ['kick', 'Cancel + kick']], 'cancel'),
      int('strikes', 'Strikes before kick', 1, 100, 10, { unit: 'cancelled messages / 60 s' }),
    ],
  },
]

// ───────────────────────────── presets ─────────────────────────────

export interface PresetDef {
  id: string
  name: string
  description: string
  /** Partial overrides on top of the defaults. */
  overrides: Record<string, Record<string, FieldValue>>
}

export const PRESETS: PresetDef[] = [
  {
    id: 'balanced',
    name: 'Balanced (recommended)',
    description: 'Safe defaults: connection protection is enforced, riskier detectors only watch.',
    overrides: {},
  },
  {
    id: 'strict',
    name: 'Strict',
    description: 'Tight limits, kicks abusive clients. Expect the occasional false positive – check the event log.',
    overrides: {
      connectionFlood: { mode: 'enforce', maxAttemptsPerIp: 5, maxAttemptsPerLicense: 4, banSec: 900 },
      playersPerIp: { mode: 'enforce', maxPlayers: 3 },
      identityCheck: { mode: 'enforce' },
      attackMode: { mode: 'auto', triggerBlockedPerMin: 25, triggerAttemptsPerMin: 150, newPlayers: 'block', limitPercent: 40 },
      gameEventFlood: { mode: 'enforce', maxExplosions: 8, maxParticles: 40, maxFires: 10, maxProjectiles: 15, action: 'kick', strikes: 15 },
      entitySpam: { mode: 'enforce', maxEntities: 30, action: 'cancel' },
      chatFlood: { mode: 'enforce', maxMessages: 5, maxLength: 300 },
    },
  },
  {
    id: 'monitor',
    name: 'Monitor only (learning mode)',
    description: 'Nothing is blocked. Every detector reports what it would have done – ideal for the first days on a new server.',
    overrides: {
      connectionFlood: { mode: 'monitor' },
      playersPerIp: { mode: 'monitor' },
      identityCheck: { mode: 'monitor' },
      attackMode: { mode: 'monitor' },
      gameEventFlood: { mode: 'monitor' },
      entitySpam: { mode: 'monitor' },
      entityLockdown: { mode: 'off' },
      chatFlood: { mode: 'monitor' },
    },
  },
]

// ───────────────────────────── normalisation ─────────────────────────────

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/* eslint-disable no-control-regex */
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/g

export function normalizeField(def: Field, value: unknown): FieldValue {
  switch (def.type) {
    case 'int': {
      const n = typeof value === 'number' ? value : typeof value === 'string' && value.trim() !== '' ? Number(value) : NaN
      if (!Number.isFinite(n)) return def.default
      return Math.min(def.max, Math.max(def.min, Math.round(n)))
    }
    case 'bool':
      return typeof value === 'boolean' ? value : def.default
    case 'select':
      return typeof value === 'string' && def.options.some((o) => o.value === value) ? value : def.default
    case 'text': {
      if (typeof value !== 'string') return def.default
      const s = value.replace(CONTROL_CHARS, ' ').trim().slice(0, def.maxLength)
      return s === '' ? def.default : s
    }
  }
}

export function normalizeConfig(input: unknown): Config {
  const raw = isPlainObject(input) ? input : {}
  const rawGeneral = isPlainObject(raw.general) ? raw.general : {}
  const rawProtections = isPlainObject(raw.protections) ? raw.protections : {}
  const rawMessages = isPlainObject(raw.messages) ? raw.messages : {}

  const general: Record<string, FieldValue> = {}
  for (const f of GENERAL_FIELDS) general[f.key] = normalizeField(f, rawGeneral[f.key])

  const protections: Record<string, Record<string, FieldValue>> = {}
  for (const def of PROTECTIONS) {
    const rp = isPlainObject(rawProtections[def.id]) ? (rawProtections[def.id] as Record<string, unknown>) : {}
    const out: Record<string, FieldValue> = {}
    out.mode = typeof rp.mode === 'string' && def.modes.some((m) => m.value === rp.mode) ? rp.mode : def.defaultMode
    for (const f of def.fields) out[f.key] = normalizeField(f, rp[f.key])
    protections[def.id] = out
  }

  const messages: Record<string, string> = {}
  for (const f of MESSAGE_FIELDS) messages[f.key] = normalizeField(f, rawMessages[f.key]) as string

  return { v: CONFIG_VERSION, general, protections, messages }
}

export function defaultConfig(): Config {
  return normalizeConfig({})
}

/** Deep-merge `patch` (partial config) onto `base`, then normalise. */
export function mergeConfig(base: Config, patch: unknown): Config {
  const p = isPlainObject(patch) ? patch : {}
  const pProt = isPlainObject(p.protections) ? p.protections : {}
  const merged = {
    general: { ...base.general, ...(isPlainObject(p.general) ? p.general : {}) },
    protections: Object.fromEntries(
      PROTECTIONS.map((d) => [d.id, { ...base.protections[d.id], ...(isPlainObject(pProt[d.id]) ? (pProt[d.id] as object) : {}) }]),
    ),
    messages: { ...base.messages, ...(isPlainObject(p.messages) ? p.messages : {}) },
  }
  return normalizeConfig(merged)
}

export function presetConfig(id: string): Config | null {
  const preset = PRESETS.find((p) => p.id === id)
  if (!preset) return null
  const base = defaultConfig()
  // presets only change protections, never general settings or messages
  return mergeConfig(base, { protections: preset.overrides })
}

/** JSON-serialisable catalog for the dashboard. */
export function catalogForClient() {
  return {
    version: CONFIG_VERSION,
    general: GENERAL_FIELDS,
    messages: MESSAGE_FIELDS,
    protections: PROTECTIONS,
    presets: PRESETS.map((p) => ({ id: p.id, name: p.name, description: p.description, config: presetConfig(p.id) })),
    defaults: defaultConfig(),
  }
}
